services:
  - type: web
    name: apporders-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: apporders-server
          property: port
      - key: SHOPIFY_STORE_URL
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
    healthCheckPath: /health